### ISSUE TITLE
how to running the code?

### ISSUE THREAD

**Issue by arthurfsy2** [williamtriinh/nrc-to-strava#3]
hi, william
   Could you briefly explain how to run this program? I have downloaded the script and made sure the python version is 3.11.2
BTW, Can this script be run from the command line?

**Comment by williamtriinh** [comment]
Hi. Sorry for the late reply, I didn't notice this. You can run it by using the command `python src/main.py`. You'll need to install `textual` using `pip install textual` (more information [here](https://textual.textualize.io/getting_started)). ~~I'll update the readme when I get the chance~~.

I've updated the readme with a bit more details.

**Comment by arthurfsy2** [comment]
Thanks!
